project:
  type: website

website:
  title: "GIRLY SCIENCE"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/soffpin/GIRLY-SCIENCE
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: source

